version: '4'
services:
  product_db:
    image: mongo:7.0.5
    container_name: product_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data/product_db:/data/db
  order_db:
    image: mysql:8.4.2
    container_name: order_db
    environment:
      MYSQL_ROOT_PASSWORD: order_db
    ports:
      - "3306:3306"
    volumes:
      - ./data/order_db:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
  inventory_db:
    image: postgres:16.4
    container_name: inventory_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_service
    ports:
      - "5432:5432"
    volumes:
      - ./data/inventory_db:/var/lib/postgresql

  keycloak_db:
    container_name: keycloak_db
    image: mysql:8.3.0
    volumes:
      - ./data/keycloak_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak_db